### ISSUE TITLE
Readme typo?

### ISSUE THREAD

**Issue by johnhilts** [ashok-khanna/ParEvil#1]
> “reinvest the wheel”

did you mean “reinvent“?

**Comment by ashok-khanna** [comment]
> > “reinvest the wheel”
> 
> 
> 
> did you mean “reinvent“?

Yes I did :) Thanks for picking up, I'll edit when I'm back on a computer

**Comment by ashok-khanna** [comment]
Fixed :) Thanks again, closing now.
